apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - proxy-headers.yaml
  - health-egress.patch.yaml
patches:
  - path: values.patch.yaml
  - path: probes.patch.yaml
  - path: ingress.patch.yaml
  - path: proxy-policy.patch.yaml
  - path: verifier-tls.patch.yaml
