// issuer/src/webauthn/handlers.rs
use axum::{
    extract::{Json, State},
    http::StatusCode,
    routing::{get, post},
    Router,
};
use base64ct::Encoding;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{debug, info, warn};
use uuid::Uuid;
use webauthn_rs::prelude::*;

use super::ctx::WebAuthnCtx;
use super::store::CredentialStore;

// --- Proof Generation Utilities ---

/// Derive a proof verification key from the RP ID
/// This must match the derivation in gate.rs for verification to work
fn derive_proof_key(rp_id: &str) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new_keyed(&[0u8; 32]);
    hasher.update(b"webauthn:proof:key:v1:");
    hasher.update(rp_id.as_bytes());

    // Use system entropy if available, otherwise use RP ID as deterministic seed
    if let Ok(secret) = std::env::var("WEBAUTHN_PROOF_SECRET") {
        hasher.update(secret.as_bytes());
    } else {
        // Fallback: derive from RP ID (deterministic but unique per deployment)
        hasher.update(b":deterministic");
    }

    *hasher.finalize().as_bytes()
}

/// Compute authentication proof for Sybil resistance
/// This proof can only be generated by the server (requires secret key)
fn compute_auth_proof(rp_id: &str, username: &str, timestamp: i64) -> String {
    let proof_key = derive_proof_key(rp_id);
    let mut hasher = blake3::Hasher::new_keyed(&proof_key);
    hasher.update(b"webauthn:auth:");
    hasher.update(username.as_bytes());
    hasher.update(b":");
    hasher.update(&timestamp.to_le_bytes());
    base64ct::Base64UrlUnpadded::encode_string(hasher.finalize().as_bytes())
}

// --- State ---

#[derive(Clone)]
pub struct WebAuthnState {
    pub webauthn: Arc<WebAuthnCtx>,
    pub cred_store: CredentialStore,
    pub sessions: Arc<RwLock<HashMap<String, SessionData>>>,
}

#[derive(Clone, Debug)]
pub enum SessionData {
    Registration {
        state: PasskeyRegistration,
        username: String,
        created_at: i64,
    },
    Authentication {
        state: PasskeyAuthentication,
        username: String,
        created_at: i64,
    },
}

impl SessionData {
    pub fn is_expired(&self) -> bool {
        let now = chrono::Utc::now().timestamp();
        let created_at = match self {
            SessionData::Registration { created_at, .. } => *created_at,
            SessionData::Authentication { created_at, .. } => *created_at,
        };
        now - created_at > 900 // 15 minutes
    }
}

// --- Router Factory ---

pub fn router(state: Arc<WebAuthnState>) -> Router {
    let use_attestation = std::env::var("WEBAUTHN_REQUIRE_ATTESTATION")
        .unwrap_or_else(|_| "false".to_string())
        .eq_ignore_ascii_case("true");

    if use_attestation {
        Router::new()
            .route("/register/start", post(start_registration))
            .route("/register/finish", post(finish_registration_with_attestation))
            .route("/authenticate/start", post(start_authentication))
            .route("/authenticate/finish", post(finish_authentication))
            .route("/info", get(webauthn_info))
            .with_state(state)
    } else {
        Router::new()
            .route("/register/start", post(start_registration))
            .route("/register/finish", post(finish_registration))
            .route("/authenticate/start", post(start_authentication))
            .route("/authenticate/finish", post(finish_authentication))
            .route("/info", get(webauthn_info))
            .with_state(state)
    }
}

// --- Handlers ---

#[derive(Debug, Deserialize)]
pub struct StartRegistrationRequest {
    pub username: String,
    pub display_name: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct StartRegistrationResponse {
    pub options: CreationChallengeResponse,
    pub session_id: String,
}

pub async fn start_registration(
    State(state): State<Arc<WebAuthnState>>,
    Json(req): Json<StartRegistrationRequest>,
) -> Result<Json<StartRegistrationResponse>, (StatusCode, String)> {
    debug!(username = %req.username, "Starting WebAuthn registration");

    let user_id_hash = {
        use blake3::Hasher;
        let mut hasher = Hasher::new();
        hasher.update(b"webauthn:user:");
        hasher.update(req.username.as_bytes());
        hasher.finalize().to_hex().to_string()
    };

    let existing_creds = state
        .cred_store
        .load_user_credentials(&user_id_hash)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    if !existing_creds.is_empty() {
        warn!(
            username = %req.username,
            cred_count = existing_creds.len(),
            "User already has registered credentials"
        );
        // Generic error message to prevent username enumeration
        // Don't reveal whether the user exists or how many credentials they have
        return Err((
            StatusCode::CONFLICT,
            "Registration not available for this username".to_string(),
        ));
    }

    let exclude_credentials = if existing_creds.is_empty() {
        None
    } else {
        Some(
            existing_creds
                .iter()
                .map(|c| c.cred_id.clone().into())
                .collect(),
        )
    };

    // webauthn-rs 0.5.3 API: start_passkey_registration(uuid, username, display_name, exclude)
    let (options, reg_state) = state
        .webauthn
        .webauthn
        .start_passkey_registration(
            Uuid::new_v4(),
            &req.username,
            &req.display_name
                .clone()
                .unwrap_or_else(|| req.username.clone()),
            exclude_credentials,
        )
        .map_err(|e| {
            warn!(error = %e, "Failed to start registration");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Registration start failed: {}", e),
            )
        })?;

    let session_id = uuid::Uuid::new_v4().to_string();

    {
        let mut sessions = state.sessions.write().await;
        sessions.insert(
            session_id.clone(),
            SessionData::Registration {
                state: reg_state,
                username: req.username.clone(),
                created_at: chrono::Utc::now().timestamp(),
            },
        );
        sessions.retain(|_, session| !session.is_expired());
    }

    info!(
        username = %req.username,
        session_id = %session_id,
        "Started WebAuthn registration"
    );

    Ok(Json(StartRegistrationResponse {
        options,
        session_id,
    }))
}

#[derive(Debug, Deserialize)]
pub struct FinishRegistrationRequest {
    pub session_id: String,
    pub credential: RegisterPublicKeyCredential,
}

#[derive(Debug, Serialize)]
pub struct FinishRegistrationResponse {
    pub ok: bool,
    pub cred_id: String,
    pub user_id_hash: String,
    pub registered_at: i64,
}

pub async fn finish_registration(
    State(state): State<Arc<WebAuthnState>>,
    Json(req): Json<FinishRegistrationRequest>,
) -> Result<Json<FinishRegistrationResponse>, (StatusCode, String)> {
    debug!(session_id = %req.session_id, "Finishing WebAuthn registration");

    let (reg_state, username) = {
        let mut sessions = state.sessions.write().await;
        match sessions.remove(&req.session_id) {
            Some(SessionData::Registration {
                state, username, ..
            }) => (state, username),
            Some(_) => {
                return Err((StatusCode::BAD_REQUEST, "Invalid session type".to_string()));
            }
            None => {
                return Err((
                    StatusCode::NOT_FOUND,
                    "Session not found or expired".to_string(),
                ));
            }
        }
    };

    let passkey = state
        .webauthn
        .webauthn
        .finish_passkey_registration(&req.credential, &reg_state)
        .map_err(|e| {
            warn!(error = %e, session_id = %req.session_id, "Registration failed");
            (
                StatusCode::BAD_REQUEST,
                format!("Registration failed: {}", e),
            )
        })?;

    let user_id_hash = {
        use blake3::Hasher;
        let mut hasher = Hasher::new();
        hasher.update(b"webauthn:user:");
        hasher.update(username.as_bytes());
        hasher.finalize().to_hex().to_string()
    };

    let cred_id = passkey.cred_id().clone();
    state
        .cred_store
        .save(cred_id.clone().into(), passkey, user_id_hash.clone())
        .await
        .map_err(|e| {
            warn!(error = %e, "Failed to save credential");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Failed to save credential: {}", e),
            )
        })?;

    let cred_id_b64 = base64ct::Base64UrlUnpadded::encode_string(&cred_id);

    info!(
        username = %username,
        cred_id = %cred_id_b64,
        "Completed WebAuthn registration"
    );

    Ok(Json(FinishRegistrationResponse {
        ok: true,
        cred_id: cred_id_b64,
        user_id_hash,
        registered_at: chrono::Utc::now().timestamp(),
    }))
}
// ============================================================================
// Authentication Flow
// ============================================================================

#[derive(Debug, Deserialize)]
pub struct StartAuthenticationRequest {
    pub username: String,
}

#[derive(Debug, Serialize)]
pub struct StartAuthenticationResponse {
    pub options: RequestChallengeResponse,
    pub session_id: String,
}

pub async fn start_authentication(
    State(state): State<Arc<WebAuthnState>>,
    Json(req): Json<StartAuthenticationRequest>,
) -> Result<Json<StartAuthenticationResponse>, (StatusCode, String)> {
    debug!(username = %req.username, "Starting WebAuthn authentication");

    // Add consistent minimum response time to prevent timing-based enumeration
    let start_time = std::time::Instant::now();
    const MIN_RESPONSE_TIME_MS: u64 = 100;

    let user_id_hash = {
        use blake3::Hasher;
        let mut hasher = Hasher::new();
        hasher.update(b"webauthn:user:");
        hasher.update(req.username.as_bytes());
        hasher.finalize().to_hex().to_string()
    };

    let stored_creds = state
        .cred_store
        .load_user_credentials(&user_id_hash)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    // Anti-enumeration: Return generic error for non-existent users
    // Use consistent timing to prevent timing-based enumeration attacks
    if stored_creds.is_empty() {
        debug!(username = %req.username, "No credentials found for user (returning generic error)");

        // Ensure consistent response time
        let elapsed = start_time.elapsed().as_millis() as u64;
        if elapsed < MIN_RESPONSE_TIME_MS {
            tokio::time::sleep(std::time::Duration::from_millis(MIN_RESPONSE_TIME_MS - elapsed)).await;
        }

        // Return generic error that doesn't reveal user existence
        // Same error message as other auth failures
        return Err((
            StatusCode::BAD_REQUEST,
            "Authentication failed".to_string(),
        ));
    }

    let passkeys: Vec<Passkey> = stored_creds.into_iter().map(|c| c.credential).collect();

    let (options, auth_state) = state
        .webauthn
        .webauthn
        .start_passkey_authentication(&passkeys)
        .map_err(|e| {
            warn!(error = %e, "Failed to start authentication");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                "Authentication failed".to_string(),
            )
        })?;

    let session_id = uuid::Uuid::new_v4().to_string();

    {
        let mut sessions = state.sessions.write().await;
        sessions.insert(
            session_id.clone(),
            SessionData::Authentication {
                state: auth_state,
                username: req.username.clone(),
                created_at: chrono::Utc::now().timestamp(),
            },
        );
        sessions.retain(|_, session| !session.is_expired());
    }

    // Ensure consistent response time for successful lookups too
    let elapsed = start_time.elapsed().as_millis() as u64;
    if elapsed < MIN_RESPONSE_TIME_MS {
        tokio::time::sleep(std::time::Duration::from_millis(MIN_RESPONSE_TIME_MS - elapsed)).await;
    }

    info!(
        username = %req.username,
        session_id = %session_id,
        "Started WebAuthn authentication"
    );

    Ok(Json(StartAuthenticationResponse {
        options,
        session_id,
    }))
}

#[derive(Debug, Deserialize)]
pub struct FinishAuthenticationRequest {
    pub session_id: String,
    pub credential: PublicKeyCredential,
}

#[derive(Debug, Serialize)]
pub struct FinishAuthenticationResponse {
    pub ok: bool,
    pub cred_id: String,
    pub username: String,
    pub authenticated_at: i64,
    pub proof: String,
}

pub async fn finish_authentication(
    State(state): State<Arc<WebAuthnState>>,
    Json(req): Json<FinishAuthenticationRequest>,
) -> Result<Json<FinishAuthenticationResponse>, (StatusCode, String)> {
    debug!(session_id = %req.session_id, "Finishing WebAuthn authentication");

    let (auth_state, username) = {
        let mut sessions = state.sessions.write().await;
        match sessions.remove(&req.session_id) {
            Some(SessionData::Authentication {
                state, username, ..
            }) => (state, username),
            Some(_) => {
                return Err((StatusCode::BAD_REQUEST, "Invalid session type".to_string()));
            }
            None => {
                return Err((
                    StatusCode::NOT_FOUND,
                    "Session not found or expired".to_string(),
                ));
            }
        }
    };

    let auth_result = state
        .webauthn
        .webauthn
        .finish_passkey_authentication(&req.credential, &auth_state)
        .map_err(|e| {
            warn!(error = %e, session_id = %req.session_id, "Authentication failed");
            (
                StatusCode::UNAUTHORIZED,
                format!("Authentication failed: {}", e),
            )
        })?;

    let cred_id = auth_result.cred_id();
    state.cred_store.update_last_used(cred_id).await.ok();

    let cred_id_b64 = base64ct::Base64UrlUnpadded::encode_string(cred_id);

    // Generate cryptographically secure proof for Sybil resistance
    // This proof is HMAC-based and can only be generated by the server
    let authenticated_at = chrono::Utc::now().timestamp();
    let proof = compute_auth_proof(&state.webauthn.rp_id, &username, authenticated_at);

    info!(
        username = %username,
        cred_id = %cred_id_b64,
        "Completed WebAuthn authentication"
    );

    Ok(Json(FinishAuthenticationResponse {
        ok: true,
        cred_id: cred_id_b64,
        username,
        authenticated_at,
        proof,
    }))
}

// ============================================================================
// Info Endpoint
// ============================================================================

#[derive(Debug, Serialize)]
pub struct WebAuthnInfo {
    pub rp_id: String,
    pub rp_name: String,
    pub origin: String,
}

pub async fn webauthn_info(State(state): State<Arc<WebAuthnState>>) -> Json<WebAuthnInfo> {
    Json(WebAuthnInfo {
        rp_id: state.webauthn.rp_id.clone(),
        rp_name: state.webauthn.rp_name.clone(),
        origin: state.webauthn.rp_origin.clone(),
    })
}

/// Extended finish registration with policy enforcement
pub async fn finish_registration_with_attestation(
    State(state): State<Arc<WebAuthnState>>,
    Json(req): Json<FinishRegistrationRequest>,
) -> Result<Json<FinishRegistrationResponse>, (StatusCode, String)> {
    debug!(session_id = %req.session_id, "Finishing WebAuthn registration with policy check");

    let (reg_state, username) = {
        let mut sessions = state.sessions.write().await;
        match sessions.remove(&req.session_id) {
            Some(SessionData::Registration {
                state, username, ..
            }) => (state, username),
            Some(_) => {
                return Err((StatusCode::BAD_REQUEST, "Invalid session type".to_string()));
            }
            None => {
                return Err((
                    StatusCode::NOT_FOUND,
                    "Session not found or expired".to_string(),
                ));
            }
        }
    };

    // Complete registration
    let passkey = state
        .webauthn
        .webauthn
        .finish_passkey_registration(&req.credential, &reg_state)
        .map_err(|e| {
            warn!(error = %e, session_id = %req.session_id, "Registration failed");
            (
                StatusCode::BAD_REQUEST,
                format!("Registration failed: {}", e),
            )
        })?;

    // Apply policy checks if configured
    if should_enforce_policy() {
        enforce_registration_policy(&req.credential)?;
    }

    // Continue with the existing registration flow
    let user_id_hash = {
        use blake3::Hasher;
        let mut hasher = Hasher::new();
        hasher.update(b"webauthn:user:");
        hasher.update(username.as_bytes());
        hasher.finalize().to_hex().to_string()
    };

    let cred_id = passkey.cred_id().clone();

    // Save credential
    state
        .cred_store
        .save(cred_id.clone().into(), passkey, user_id_hash.clone())
        .await
        .map_err(|e| {
            warn!(error = %e, "Failed to save credential");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Failed to save credential: {}", e),
            )
        })?;

    // Optionally store policy metadata
    if let Ok(redis_url) = std::env::var("WEBAUTHN_REDIS_URL") {
        store_registration_metadata(&redis_url, &cred_id, &username).await;
    }

    let cred_id_b64 = base64ct::Base64UrlUnpadded::encode_string(&cred_id);

    info!(
        username = %username,
        cred_id = %cred_id_b64,
        "Completed WebAuthn registration with policy enforcement"
    );

    Ok(Json(FinishRegistrationResponse {
        ok: true,
        cred_id: cred_id_b64,
        user_id_hash,
        registered_at: chrono::Utc::now().timestamp(),
    }))
}

/// Check if policy enforcement is enabled
fn should_enforce_policy() -> bool {
    std::env::var("WEBAUTHN_REQUIRE_ATTESTATION")
        .unwrap_or_else(|_| "false".to_string())
        .eq_ignore_ascii_case("true")
}

/// Enforce registration policy based on configuration
fn enforce_registration_policy(
    credential: &RegisterPublicKeyCredential,
) -> Result<(), (StatusCode, String)> {
    let policy =
        std::env::var("WEBAUTHN_ATTESTATION_POLICY").unwrap_or_else(|_| "none".to_string());

    match policy.as_str() {
        "none" => {
            info!("No attestation policy enforcement");
            Ok(())
        }
        "strict" => {
            // Check the attestation object size as a heuristic
            // Use to_vec() to get the actual bytes
            let data = credential.response.attestation_object.to_vec();
            let size = data.len();

            if size < 200 {
                // Very small attestation object likely means "none" format
                warn!("Registration rejected: attestation object too small (likely software key)");
                return Err((
                    StatusCode::FORBIDDEN,
                    "Hardware authenticator required".to_string(),
                ));
            }
            info!(
                "Registration accepted: attestation object present (size: {} bytes)",
                size
            );
            Ok(())
        }
        "log_only" => {
            // Log attestation details but don't enforce
            let data = credential.response.attestation_object.to_vec();
            let size = data.len();
            info!("Attestation object size: {} bytes", size);
            Ok(())
        }
        _ => {
            warn!("Unknown attestation policy: {}", policy);
            Ok(())
        }
    }
}

/// Store registration metadata for monitoring
async fn store_registration_metadata(redis_url: &str, cred_id: &[u8], username: &str) {
    // Store metadata about the registration for analytics
    if let Ok(client) = redis::Client::open(redis_url) {
        if let Ok(mut conn) = client.get_async_connection().await {
            let metadata = RegistrationMetadata {
                username: username.to_string(),
                registered_at: chrono::Utc::now().timestamp(),
                policy: std::env::var("WEBAUTHN_ATTESTATION_POLICY")
                    .unwrap_or_else(|_| "none".to_string()),
            };

            if let Ok(json) = serde_json::to_string(&metadata) {
                let key = format!(
                    "webauthn:metadata:{}",
                    base64ct::Base64UrlUnpadded::encode_string(cred_id)
                );

                let _: Result<(), _> = redis::cmd("SET")
                    .arg(&key)
                    .arg(&json)
                    .arg("EX")
                    .arg(86400) // 24 hour TTL for metadata
                    .query_async(&mut conn)
                    .await;

                info!("Stored registration metadata for monitoring");
            }
        }
    }
}

/// Metadata stored for each registration
#[derive(Debug, Serialize, Deserialize)]
struct RegistrationMetadata {
    username: String,
    registered_at: i64,
    policy: String,
}

// NOTE: You will need to adapt the imports in the copied code to use `super::store` etc.