apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - redis-deployment.yaml
  - issuer-deployment.yaml
  - verifier-deployment.yaml
  - network-policy.yaml
  - ingress.yaml
