apiVersion: v1
kind: ConfigMap
metadata:
  name: freebird-proxy-headers
  namespace: REQUIRED_PROXY_NAMESPACE
data:
  X-Forwarded-Proto: "https"
  X-Forwarded-For: "$remote_addr"
  X-Forwarded-Host: "$host"
  X-Forwarded-Port: "443"
